### ISSUE TITLE
Were can i find the msm460-factory.bin

### ISSUE THREAD

**Issue by MatBush1** [blocktrron/msm460-flashing#1]
Hi, i want to flash a MSM460 and don´t know were i can get the OpenWrt factory image "msm460-factory.bin"
I do not find it under https://firmware-selector.openwrt.org

Thanks for support

**Comment by blocktrron** [comment]
See https://downloads.openwrt.org/releases/23.05-SNAPSHOT/targets/mpc85xx/p1020/
